brew 'bat'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git-delta'
brew 'grex'
brew 'herdr'
brew 'hyperfine'
brew 'ncdu'
brew 'neovim'
brew 'node' # also provides npm
brew 'ripgrep'
brew 'rtk'
brew 'shellcheck'
brew 'shfmt'
brew 'starship'
brew 'tmux'
brew 'topgrade'
brew 'uv' # installs ty/ruff for pi (pi/install.sh)
brew 'zoxide'
brew 'zsh'
