#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info() {
	printf '\r  [ \033[00;34m..\033[0m ] %s\n' "$1"
}

user() {
	printf '\r  [ \033[0;33m??\033[0m ] %s\n' "$1"
}

success() {
	printf '\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n' "$1"
}

fail() {
	printf '\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n' "$1"
	echo ''
	exit 1
}

read_user_input() {
	local __resultvar=$1
	shift

	if [[ -r /dev/tty ]]; then
		read -r "$@" "${__resultvar?}" < /dev/tty
	else
		fail 'Interactive input required, but no TTY is available'
	fi
}

setup_gitconfig() {
	local git_authorname git_authoremail

	if ! [ -f git/gitconfig.local.symlink ]; then
		info 'setup gitconfig'

		git_credential='cache'
		if [ "$(uname -s)" == "Darwin" ]; then
			git_credential='osxkeychain'
		fi

		user ' - What is your github author name?'
		read_user_input git_authorname -e
		user ' - What is your github author email?'
		read_user_input git_authoremail -e

		cp git/gitconfig.local.symlink.example git/gitconfig.local.symlink
		git config --file git/gitconfig.local.symlink user.name "$git_authorname"
		git config --file git/gitconfig.local.symlink user.email "$git_authoremail"
		git config --file git/gitconfig.local.symlink credential.helper "$git_credential"

		success 'gitconfig'
	fi
}

link_file() {
	local src=$1 dst=$2

	local overwrite='' backup='' skip=''
	local action=''

	if [ -f "$dst" ] || [ -d "$dst" ] || [ -L "$dst" ]; then

		if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then

			local currentSrc
			currentSrc="$(readlink "$dst")"

			if [ "$currentSrc" == "$src" ]; then

				skip=true

			else

				user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
				read_user_input action -r -n 1
				echo ''

				case "$action" in
				o)
					overwrite=true
					;;
				O)
					overwrite_all=true
					;;
				b)
					backup=true
					;;
				B)
					backup_all=true
					;;
				s)
					skip=true
					;;
				S)
					skip_all=true
					;;
				*) ;;
				esac

			fi

		fi

		overwrite=${overwrite:-$overwrite_all}
		backup=${backup:-$backup_all}
		skip=${skip:-$skip_all}

		if [ "$overwrite" == "true" ]; then
			rm -rf "$dst"
			success "removed $dst"
		fi

		if [ "$backup" == "true" ]; then
			mv "$dst" "${dst}.backup"
			success "moved $dst to ${dst}.backup"
		fi

		if [ "$skip" == "true" ]; then
			success "skipped $src"
		fi
	fi

	if [ "$skip" != "true" ]; then # "false" or empty
		ln -s "$src" "$dst"
		success "linked $src to $dst"
	fi
}

install_dotfiles() {
	info 'installing dotfiles'

	local overwrite_all=false backup_all=false skip_all=false

	while IFS= read -r src; do
		dst="$HOME/.$(basename "${src%.*}")"
		link_file "$src" "$dst"
	done < <(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
}

setup_gitconfig
install_dotfiles
bash "$DOTFILES_ROOT/script/install"
echo '  All installed!'
